import Navigation from "../../component/navigation";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {/* <html lang="en">
      <body> */}
      {/* <Navigation /> */}
      {children}
      &copy; NextJS is great
      {/* </body>
    </html> */}
    </div>
  );
}
